format = """
$os$username$directory $git_branch$git_status
$character"""

command_timeout = 5001
add_newline = false

[os]
format = "[$symbol](bold fg:blue)"
disabled = false

[os.symbols]
Windows = " "
Arch = "󰣇 "
Ubuntu = " "
Macos = "󰀵 "

[username]
style_user = "fg:black bold bg:purple bold"
style_root = "black bold"
format = "[](bold fg:purple)[$user]($style)[ ](bold fg:purple)"
disabled = false
show_always = true

[directory]
home_symbol = "  "
read_only_style = "198"
read_only = "  "
style = "bg:purple fg:black"
format = '󰜥 [](bold fg:purple)[󰉋 $path]($style)[](bold fg:purple)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[character]
success_symbol = "[ ](bold fg:blue)"
error_symbol = "[ ](bold fg:red)"

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 13
truncation_symbol = ""
format = "[](bold fg:purple)[$symbol $branch(:$remote_branch)](fg:black bg:purple)[ ](bold fg:purple)"

